### ISSUE TITLE
体験談にpdfを投稿できる機能を追加

### ISSUE THREAD

**Issue by euglena1215** [i544c/ittern#22]
それぞれのインターンで何かしらのスライドを作ってる人は多い気がする。

オプションとして体験談にpdfを添付できる機能とかあったら
体験談をカードみたいなレイアウトで表示させようと思ったときに

スライドがある -> スライドの1枚目 (sharedocのイメージ)
スライドがない -> 企業ロゴ

みたいな形にできたら見栄えもいいんじゃないかなと思った。

NDA的にまずい情報はきちんと黒塗りしようなどの声かけがあった方が親切かも。

**Comment by euglena1215** [comment]
@i544c 
この辺の話し合いをしたいです

**Comment by defaultcf** [comment]
@euglena1215 大変便利になると思います。
あと2日間で実装出来るのであれば是非お願いしたいです:pray:

**Comment by euglena1215** [comment]
@i544c 
pdfはテキスト情報を持っている可能性がある。
なので、まずい情報がアップされるのを防ぐために一度pdfを画像化して画像化したものを表示させるようにする。

フローとしては

1. pdfがアップロードされる & reivewsテーブル is_converted: falseを設定
2. 非同期にconvertを投げる -> convertが終わったら is_converted: trueに更新
3. アプリケーション側からは `pdf: nil` or `is_converted: true` になっている体験談のみ表示

こんな感じでどうでしょう？

**Comment by euglena1215** [comment]
@i544c 
materialize-cssってNow loading...みたいなクルクルする表示あるんだっけ？
もしそれがあるなら `pdf: not nil` and `is_converted: false` でスライドの部分はクルクルとかでもよさそう

**Comment by defaultcf** [comment]
@euglena1215 
おぉ、ActiveJob使う感じですかね
面白そう

Materializeにはクルクルする表示は無いみたいですね...
CSSで頑張って実装しますね

**Comment by euglena1215** [comment]
@i544c 
DBをpostgresに変更しません？
一つの体験談に複数の画像をアップロードする機能はpostgresだとあるっぽくて...
https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Add-more-files-and-remove-single-file-when-using-default-multiple-file-uploads-feature

http://bobintornado.github.io/rails/2015/12/29/Multiple-Images-Uploading-With-CarrierWave-and-PostgreSQL-Array.html

**Comment by defaultcf** [comment]
@euglena1215 
DB変更OKです:+1:

**Comment by euglena1215** [comment]
@i544c 
pdfをjpg化、それを非同期で処理させるのは動いているのですが、
レコードに複数枚の画像を持たせるところが動いておらず時間がかかっています。。。
すみません。。。

**Comment by euglena1215** [comment]
@i544c 
解決しました。なんでこんなことにハマってたんだろう。。。

https://stackoverflow.com/questions/33401629/no-implicit-conversion-of-nil-into-string-error-for-carrierwave-multiple-image
