### ISSUE TITLE
ヘッダーを整える

### ISSUE THREAD

**Issue by defaultcf** [i544c/ittern#25]
* Ittern(タイトルでどこにもリンクせず)
* 企業情報(/)
* 体験談(/reviews)
* ユーザー名(クリックでドロップダウンメニューが開く)
  * プロフィール変更
  * ログアウト

今のところ以下のようなレイアウトを考えています。

**Comment by euglena1215** [comment]
@i544c 
🙆‍♂️
自分で設定しといてあれなんですが、rootは体験談の方が良いような気がします

**Comment by defaultcf** [comment]
@euglena1215 
なるほど、ではそうしましょう:+1:
