### ISSUE TITLE
経験談作成時にbenefitを埋めていない

### ISSUE THREAD

**Issue by defaultcf** [i544c/ittern#31]
# 現状
経験談を作成すると、交通費や宿泊場所の提供などのbenefitが埋められていないため、その経験談の詳細に遷移するとエラーが発生する。

# 解決方法
1対1のリレーションが貼ってあるモデルで、一つのページで双方の作成って出来るんですかね...？
出来なければ、現状の状態のままbenefit抜きの状態でReviewだけ作成してしまって、経験談詳細に遷移する際にそのReviewのbenefitが存在するか確認。benefitが無くて且つ閲覧者がその経験談の作成者だったらbenefitを埋めるページに遷移、作成者でなければ404を返す、といった処理を作成する必要があるかと思われます。

**Comment by defaultcf** [comment]
@euglena1215 
大問題を発見しました...

**Comment by euglena1215** [comment]
@i544c 
> 1対1のリレーションが貼ってあるモデルで、一つのページで双方の作成って出来るんですかね...？

できます！
すみません、これは完全に手抜きの結果ですね、、、
対応します
