### ISSUE TITLE
タグ機能の追加

### ISSUE THREAD

**Issue by euglena1215** [i544c/ittern#7]
CompanyとReviewに対しタグをつけられるようにする。
acts-as-taggable-onを利用する。
https://github.com/mbleigh/acts-as-taggable-on

重そうであればそれぞれissueを切り分ける。

**Comment by euglena1215** [comment]
@i544c 
bootstrapにはtagsinputってのがあって良い感じのタグが表示されるんですけど、semantic uiにもタグを良い感じに表示させてくれる機能ある感じです？

**Comment by defaultcf** [comment]
@euglena1215 ゴメン、気付かずにcloseしちゃってました。
使おうかと思っていたSemanticUIやUIKitにはそのような機能は無いですね...
MaterializeCSSにはあります。
http://materializecss.com/chips.html
